flowchart TD
    Run["run_tests()"]
    Start["add start game step"]
    AddMovement["add test steps by calling provide_steps()"]
    Quit["add quit game step to queue"]
    Repeat[".. repeat above for each test .."]
    UnfinishedSteps{"UnfinishedSteps == 0 ?"}
    Send["send_step_from_queue()"]
    Update["Update() - loop"]
    IncreaseWaiting["UnfinishedSteps ++"]
    DecreaseWaiting["UnfinishedSteps --"]
    ExecuteStep["execute_step()"]
    StepsWaiting{"Steps  waiting ?"}

    Run --> Quit --> Start --> AddMovement --> Repeat --> Update
    Update --> UnfinishedSteps
    Update --> StepsWaiting -- Yes--> ExecuteStep --> DecreaseWaiting

    UnfinishedSteps -- Yes -->   Send --> IncreaseWaiting