flowchart TD
    Run["run_tests()"]
    Start["Add start game step"]
    AddMovement["Add movement_test by calling provide_steps()"]
    Quit["Add quit game step"]
    Repeat["Repeat for each test .."]
    UnfinishedSteps{"UnfinishedSteps == 0 ?"}
    Send["send_step_from_queue()"]
    Update["Update() - loop"]
    IncreaseUnfinished["UnfinishedSteps ++"]
    DecreaseUnfinished["UnfinishedSteps --"]
    ExecuteStep["execute_step()"]
    UnfinishedSteps{"Unfinished Steps ?"}

    Run -->  Start --> AddMovement -->  Repeat --> Quit --> Update
    UnfinishedSteps --> Update
    Update --> UnfinishedSteps -- Yes--> ExecuteStep --> DecreaseUnfinished

    UnfinishedSteps -- No -->   Send --> IncreaseUnfinished