%% Mermaid class diagram
classDiagram
    class GameController{
    }
    class Terrain {
        on_init()
        on_quit()
    }
    class Camera {
        on_init()
        on_quit()
    }
    class Player {
        on_init()
        on_quit()
        on_move()
    }
    class Interaction {
        move_player()
    }
    class GameState {
        <<state>>
        Uninitialized
        Initializing
        Running
        Quitting
    }
    class PlayerMove {
        <<event>>
        Direction direction
        bool active
    }
    class StateCompletionCounter {
        <<resource>>
    }
    class StartGame {
        <<event>>
    }
    class QuitGame{
        <<event>>
    }
    GameController --> Interaction
    GameController --> GameState
    GameController --> Player
    GameState ..> Terrain
    GameState ..> Camera
    GameState ..> Player
    Interaction --> PlayerMove
    PlayerMove ..> Player
    Terrain --> StateCompletionCounter
    Camera --> StateCompletionCounter
    Player --> StateCompletionCounter
    StateCompletionCounter ..> GameController
    StartGame ..> GameController
    QuitGame..> GameController
