%% Mermaid class diagram
classDiagram
    class GameController{
    }
    class Terrain {
        on_init()
        on_quit()
    }
    class Camera {
        on_init()
        on_quit()
    }
    class Player {
        on_init()
        on_quit()
        on_move()
    }
    class Interaction {
        move()
    }
    class GameState {
        <<state>>
        Uninitialized
        Initializing
        Running
        Quitting
    }
    class Move {
        <<event>>
        Direction direction
        bool active
    }
    class CompletionCounter {
        <<resource>>
    }
    class Start {
        <<event>>
    }
    class Quit {
        <<event>>
    }
    GameController --> Interaction
    GameController --> GameState
    GameController --> Player
    GameState ..> Terrain
    GameState ..> Camera
    GameState ..> Player
    Interaction --> Move
    Move ..> Player
    Terrain --> CompletionCounter
    Camera --> CompletionCounter
    Player --> CompletionCounter
    CompletionCounter ..> GameController
    Start ..> GameController
    Quit ..> GameController
