%% Mermaid class diagram
classDiagram
    class GameController{
        on_restart()
    }
    class Terrain {
        on_init()
    }
    class Camera {
        on_init()
    }
    class Player {
        on_init()
        on_move()
    }
    class Interaction {
        move()
    }
    class GameState {
        <<state>>
        Start
        Initializing
        Running
        Over
    }
    class Move {
        <<event>>
        Direction direction
        bool active
    }
    class InitCompleteEvent {
        <<event>>
        CompletedType type
    }
    class Restart {
        <<event>>
    }
    GameController --> Interaction
    GameController --> GameState
    GameController --> Player
    GameState ..> Terrain
    GameState ..> Camera
    GameState ..> Player
    Interaction --> Move
    Move ..> Player
    Terrain --> InitCompleteEvent
    Camera --> InitCompleteEvent
    Player --> InitCompleteEvent
    InitCompleteEvent ..> GameController
    Restart ..> GameController
